/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Espace_admin (void);
GtkWidget* create_Login (void);
GtkWidget* create_Ajout_agent (void);
GtkWidget* create_Modifier_agent (void);
GtkWidget* create_profil_admin (void);
GtkWidget* create_Modifier_admin (void);
