/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Espace_admin (void)
{
  GtkWidget *Espace_admin;
  GtkWidget *fixed1;
  GtkWidget *alignment1;
  GtkWidget *eventbox1;
  GtkWidget *button_deconnecter_admin;
  GtkWidget *alignment2;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *alignment3;
  GtkWidget *eventbox2;
  GtkWidget *button_profil_admin;
  GtkWidget *alignment4;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *alignment5;
  GtkWidget *eventbox3;
  GtkWidget *label24;
  GtkWidget *eventbox4;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *treeview_liste_agents_par_admin;
  GtkWidget *alignment6;
  GtkWidget *eventbox5;
  GtkWidget *button_supprimer_agents_par_admin;
  GtkWidget *alignment7;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label3;
  GtkWidget *alignment8;
  GtkWidget *eventbox6;
  GtkWidget *button_modifier_agents_par_admin;
  GtkWidget *alignment9;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label4;
  GtkWidget *alignment10;
  GtkWidget *eventbox7;
  GtkWidget *button_ajouter_agents_par_admin;
  GtkWidget *alignment11;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label5;
  GtkWidget *alignment12;
  GtkWidget *eventbox8;
  GtkWidget *button_afficher_agents_par_admin;
  GtkWidget *alignment13;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label6;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *alignment64;
  GtkWidget *eventbox53;
  GtkWidget *label29;
  GtkWidget *image33;
  GtkWidget *label27;
  GtkWidget *fixed6;
  GtkWidget *alignment65;
  GtkWidget *eventbox54;
  GtkWidget *label30;
  GtkWidget *alignment119;
  GtkWidget *eventbox100;
  GtkWidget *button_cam_agents;
  GtkWidget *alignment120;
  GtkWidget *hbox20;
  GtkWidget *image34;
  GtkWidget *label65;
  GtkWidget *image36;
  GtkWidget *label28;
  GtkWidget *fixed9;
  GtkWidget *alignment121;
  GtkWidget *eventbox101;
  GtkWidget *label69;
  GtkWidget *alignment122;
  GtkWidget *eventbox102;
  GtkWidget *button_rechercher_agent_par_admin;
  GtkWidget *alignment123;
  GtkWidget *hbox21;
  GtkWidget *image35;
  GtkWidget *label68;
  GtkWidget *treeview_coord_agents;
  GtkWidget *alignment124;
  GtkWidget *eventbox103;
  GtkWidget *entry_recherche_cinagent;
  GtkWidget *label66;
  GtkWidget *image20;

  Espace_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_admin), _("Espace_admin"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Espace_admin), fixed1);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_fixed_put (GTK_FIXED (fixed1), alignment1, 794, 20);
  gtk_widget_set_size_request (alignment1, 134, 40);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), eventbox1);

  button_deconnecter_admin = gtk_button_new ();
  gtk_widget_show (button_deconnecter_admin);
  gtk_container_add (GTK_CONTAINER (eventbox1), button_deconnecter_admin);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_deconnecter_admin), alignment2);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Se deconnecter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_fixed_put (GTK_FIXED (fixed1), alignment3, 652, 20);
  gtk_widget_set_size_request (alignment3, 134, 40);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_container_add (GTK_CONTAINER (alignment3), eventbox2);

  button_profil_admin = gtk_button_new ();
  gtk_widget_show (button_profil_admin);
  gtk_container_add (GTK_CONTAINER (eventbox2), button_profil_admin);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_profil_admin), alignment4);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-orientation-landscape", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Mon Profil"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  alignment5 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment5);
  gtk_fixed_put (GTK_FIXED (fixed1), alignment5, 57, 20);
  gtk_widget_set_size_request (alignment5, 134, 40);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_container_add (GTK_CONTAINER (alignment5), eventbox3);

  label24 = gtk_label_new (_("<span foreground=\"darkcyan\"size=\"xx-large\"><i><b>Sky Travel</b></i></span>"));
  gtk_widget_show (label24);
  gtk_container_add (GTK_CONTAINER (eventbox3), label24);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox4, 0, 104);
  gtk_widget_set_size_request (eventbox4, 936, 584);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (eventbox4), notebook1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  treeview_liste_agents_par_admin = gtk_tree_view_new ();
  gtk_widget_show (treeview_liste_agents_par_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_liste_agents_par_admin, 32, 72);
  gtk_widget_set_size_request (treeview_liste_agents_par_admin, 776, 416);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment6);
  gtk_fixed_put (GTK_FIXED (fixed2), alignment6, 778, 500);
  gtk_widget_set_size_request (alignment6, 134, 40);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), eventbox5);

  button_supprimer_agents_par_admin = gtk_button_new ();
  gtk_widget_show (button_supprimer_agents_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox5), button_supprimer_agents_par_admin);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_supprimer_agents_par_admin), alignment7);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  alignment8 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment8);
  gtk_fixed_put (GTK_FIXED (fixed2), alignment8, 632, 500);
  gtk_widget_set_size_request (alignment8, 134, 40);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_container_add (GTK_CONTAINER (alignment8), eventbox6);

  button_modifier_agents_par_admin = gtk_button_new ();
  gtk_widget_show (button_modifier_agents_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox6), button_modifier_agents_par_admin);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_modifier_agents_par_admin), alignment9);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  alignment10 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment10);
  gtk_fixed_put (GTK_FIXED (fixed2), alignment10, 488, 500);
  gtk_widget_set_size_request (alignment10, 134, 40);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_container_add (GTK_CONTAINER (alignment10), eventbox7);

  button_ajouter_agents_par_admin = gtk_button_new ();
  gtk_widget_show (button_ajouter_agents_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox7), button_ajouter_agents_par_admin);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_ajouter_agents_par_admin), alignment11);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  alignment12 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment12);
  gtk_fixed_put (GTK_FIXED (fixed2), alignment12, 817, 230);
  gtk_widget_set_size_request (alignment12, 105, 40);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_container_add (GTK_CONTAINER (alignment12), eventbox8);

  button_afficher_agents_par_admin = gtk_button_new ();
  gtk_widget_show (button_afficher_agents_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox8), button_afficher_agents_par_admin);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_afficher_agents_par_admin), alignment13);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 744, 8);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 728, 40);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 824, 96);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 824, 144);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 840, 192);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed2), entry6, 808, 288);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  alignment64 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment64);
  gtk_fixed_put (GTK_FIXED (fixed2), alignment64, 171, 12);
  gtk_widget_set_size_request (alignment64, 493, 50);

  eventbox53 = gtk_event_box_new ();
  gtk_widget_show (eventbox53);
  gtk_container_add (GTK_CONTAINER (alignment64), eventbox53);

  label29 = gtk_label_new (_("<span foreground=\"deeppink\"size=\"xx-large\"><i><b>Bienvenue dans l'espace administration !</b></i></span>"));
  gtk_widget_show (label29);
  gtk_container_add (GTK_CONTAINER (eventbox53), label29);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  image33 = create_pixmap (Espace_admin, "1916561.jpg");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed2), image33, 0, 0);
  gtk_widget_set_size_request (image33, 936, 552);

  label27 = gtk_label_new (_("<span foreground=\"black\"size=\"medium\"><b>Gestion des agents</b></span>"));
  gtk_widget_show (label27);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label27);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  alignment65 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment65);
  gtk_fixed_put (GTK_FIXED (fixed6), alignment65, 292, 40);
  gtk_widget_set_size_request (alignment65, 308, 64);

  eventbox54 = gtk_event_box_new ();
  gtk_widget_show (eventbox54);
  gtk_container_add (GTK_CONTAINER (alignment65), eventbox54);

  label30 = gtk_label_new (_("<span foreground=\"deeppink\"size=\"xx-large\"><i><b>Surveillance interne</b></i></span>"));
  gtk_widget_show (label30);
  gtk_container_add (GTK_CONTAINER (eventbox54), label30);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  alignment119 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment119);
  gtk_fixed_put (GTK_FIXED (fixed6), alignment119, 378, 152);
  gtk_widget_set_size_request (alignment119, 150, 40);

  eventbox100 = gtk_event_box_new ();
  gtk_widget_show (eventbox100);
  gtk_container_add (GTK_CONTAINER (alignment119), eventbox100);

  button_cam_agents = gtk_button_new ();
  gtk_widget_show (button_cam_agents);
  gtk_container_add (GTK_CONTAINER (eventbox100), button_cam_agents);

  alignment120 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment120);
  gtk_container_add (GTK_CONTAINER (button_cam_agents), alignment120);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment120), hbox20);

  image34 = gtk_image_new_from_stock ("gtk-media-record", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox20), image34, FALSE, FALSE, 0);

  label65 = gtk_label_new_with_mnemonic (_("Camera"));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox20), label65, FALSE, FALSE, 0);

  image36 = create_pixmap (Espace_admin, "images.png");
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed6), image36, 328, 280);
  gtk_widget_set_size_request (image36, 261, 93);

  label28 = gtk_label_new (_("<span foreground=\"black\"size=\"medium\"><b>Camera Surveillance</b></span>"));
  gtk_widget_show (label28);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label28);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  alignment121 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment121);
  gtk_fixed_put (GTK_FIXED (fixed9), alignment121, 185, 56);
  gtk_widget_set_size_request (alignment121, 533, 45);

  eventbox101 = gtk_event_box_new ();
  gtk_widget_show (eventbox101);
  gtk_container_add (GTK_CONTAINER (alignment121), eventbox101);

  label69 = gtk_label_new (_("<span foreground=\"black\"size=\"medium\"><b>Saisissez le Num_CIN de l'agent dont on veut afficher les coordonn\303\251es</b></span>"));
  gtk_widget_show (label69);
  gtk_container_add (GTK_CONTAINER (eventbox101), label69);
  gtk_label_set_use_markup (GTK_LABEL (label69), TRUE);

  alignment122 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment122);
  gtk_fixed_put (GTK_FIXED (fixed9), alignment122, 460, 125);
  gtk_widget_set_size_request (alignment122, 150, 35);

  eventbox102 = gtk_event_box_new ();
  gtk_widget_show (eventbox102);
  gtk_container_add (GTK_CONTAINER (alignment122), eventbox102);

  button_rechercher_agent_par_admin = gtk_button_new ();
  gtk_widget_show (button_rechercher_agent_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox102), button_rechercher_agent_par_admin);

  alignment123 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment123);
  gtk_container_add (GTK_CONTAINER (button_rechercher_agent_par_admin), alignment123);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment123), hbox21);

  image35 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox21), image35, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox21), label68, FALSE, FALSE, 0);

  treeview_coord_agents = gtk_tree_view_new ();
  gtk_widget_show (treeview_coord_agents);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview_coord_agents, 152, 208);
  gtk_widget_set_size_request (treeview_coord_agents, 576, 280);

  alignment124 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment124);
  gtk_fixed_put (GTK_FIXED (fixed9), alignment124, 232, 125);
  gtk_widget_set_size_request (alignment124, 183, 35);

  eventbox103 = gtk_event_box_new ();
  gtk_widget_show (eventbox103);
  gtk_container_add (GTK_CONTAINER (alignment124), eventbox103);

  entry_recherche_cinagent = gtk_entry_new ();
  gtk_widget_show (entry_recherche_cinagent);
  gtk_container_add (GTK_CONTAINER (eventbox103), entry_recherche_cinagent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_recherche_cinagent), 8226);

  label66 = gtk_label_new (_("<span foreground=\"black\"size=\"medium\"><b>Agents</b></span>"));
  gtk_widget_show (label66);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label66);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);

  image20 = create_pixmap (Espace_admin, "avion.jpg");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed1), image20, 0, 0);
  gtk_widget_set_size_request (image20, 936, 104);

  g_signal_connect ((gpointer) button_deconnecter_admin, "clicked",
                    G_CALLBACK (on_button_deconnecter_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_profil_admin, "clicked",
                    G_CALLBACK (on_button_profil_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_liste_agents_par_admin, "row_activated",
                    G_CALLBACK (on_treeview_liste_agents_par_admin_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_agents_par_admin, "clicked",
                    G_CALLBACK (on_button_supprimer_agents_par_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_agents_par_admin, "clicked",
                    G_CALLBACK (on_button_modifier_agents_par_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_agents_par_admin, "clicked",
                    G_CALLBACK (on_button_ajouter_agents_par_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_agents_par_admin, "clicked",
                    G_CALLBACK (on_button_afficher_agents_par_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cam_agents, "clicked",
                    G_CALLBACK (on_button_cam_agents_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rechercher_agent_par_admin, "clicked",
                    G_CALLBACK (on_button_rechercher_agent_par_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_admin, Espace_admin, "Espace_admin");
  GLADE_HOOKUP_OBJECT (Espace_admin, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (Espace_admin, button_deconnecter_admin, "button_deconnecter_admin");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Espace_admin, image1, "image1");
  GLADE_HOOKUP_OBJECT (Espace_admin, label1, "label1");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (Espace_admin, button_profil_admin, "button_profil_admin");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Espace_admin, image2, "image2");
  GLADE_HOOKUP_OBJECT (Espace_admin, label2, "label2");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (Espace_admin, label24, "label24");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (Espace_admin, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Espace_admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Espace_admin, treeview_liste_agents_par_admin, "treeview_liste_agents_par_admin");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (Espace_admin, button_supprimer_agents_par_admin, "button_supprimer_agents_par_admin");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Espace_admin, image4, "image4");
  GLADE_HOOKUP_OBJECT (Espace_admin, label3, "label3");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (Espace_admin, button_modifier_agents_par_admin, "button_modifier_agents_par_admin");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Espace_admin, image5, "image5");
  GLADE_HOOKUP_OBJECT (Espace_admin, label4, "label4");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (Espace_admin, button_ajouter_agents_par_admin, "button_ajouter_agents_par_admin");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Espace_admin, image6, "image6");
  GLADE_HOOKUP_OBJECT (Espace_admin, label5, "label5");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (Espace_admin, button_afficher_agents_par_admin, "button_afficher_agents_par_admin");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Espace_admin, image7, "image7");
  GLADE_HOOKUP_OBJECT (Espace_admin, label6, "label6");
  GLADE_HOOKUP_OBJECT (Espace_admin, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (Espace_admin, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Espace_admin, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Espace_admin, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Espace_admin, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Espace_admin, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment64, "alignment64");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox53, "eventbox53");
  GLADE_HOOKUP_OBJECT (Espace_admin, label29, "label29");
  GLADE_HOOKUP_OBJECT (Espace_admin, image33, "image33");
  GLADE_HOOKUP_OBJECT (Espace_admin, label27, "label27");
  GLADE_HOOKUP_OBJECT (Espace_admin, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment65, "alignment65");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox54, "eventbox54");
  GLADE_HOOKUP_OBJECT (Espace_admin, label30, "label30");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment119, "alignment119");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox100, "eventbox100");
  GLADE_HOOKUP_OBJECT (Espace_admin, button_cam_agents, "button_cam_agents");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment120, "alignment120");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Espace_admin, image34, "image34");
  GLADE_HOOKUP_OBJECT (Espace_admin, label65, "label65");
  GLADE_HOOKUP_OBJECT (Espace_admin, image36, "image36");
  GLADE_HOOKUP_OBJECT (Espace_admin, label28, "label28");
  GLADE_HOOKUP_OBJECT (Espace_admin, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment121, "alignment121");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox101, "eventbox101");
  GLADE_HOOKUP_OBJECT (Espace_admin, label69, "label69");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment122, "alignment122");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox102, "eventbox102");
  GLADE_HOOKUP_OBJECT (Espace_admin, button_rechercher_agent_par_admin, "button_rechercher_agent_par_admin");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment123, "alignment123");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Espace_admin, image35, "image35");
  GLADE_HOOKUP_OBJECT (Espace_admin, label68, "label68");
  GLADE_HOOKUP_OBJECT (Espace_admin, treeview_coord_agents, "treeview_coord_agents");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment124, "alignment124");
  GLADE_HOOKUP_OBJECT (Espace_admin, eventbox103, "eventbox103");
  GLADE_HOOKUP_OBJECT (Espace_admin, entry_recherche_cinagent, "entry_recherche_cinagent");
  GLADE_HOOKUP_OBJECT (Espace_admin, label66, "label66");
  GLADE_HOOKUP_OBJECT (Espace_admin, image20, "image20");

  gtk_widget_grab_default (image20);
  return Espace_admin;
}

GtkWidget*
create_Login (void)
{
  GtkWidget *Login;
  GtkWidget *eventbox35;
  GtkWidget *fixed3;
  GtkWidget *alignment15;
  GtkWidget *eventbox10;
  GtkWidget *label_identifiant_admin;
  GtkWidget *alignment16;
  GtkWidget *eventbox11;
  GtkWidget *label_mdp_admin;
  GtkWidget *alignment17;
  GtkWidget *eventbox12;
  GtkWidget *identifiant_entry;
  GtkWidget *alignment18;
  GtkWidget *eventbox13;
  GtkWidget *password_entry;
  GtkWidget *alignment19;
  GtkWidget *eventbox14;
  GtkWidget *button_identifier_admin;
  GtkWidget *alignment20;
  GtkWidget *hbox7;
  GtkWidget *image9;
  GtkWidget *label10;
  GtkWidget *alignment21;
  GtkWidget *eventbox15;
  GtkWidget *output_login;
  GtkWidget *alignment43;
  GtkWidget *eventbox34;
  GtkWidget *label13;
  GtkWidget *image26;

  Login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Login), _("Login"));

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_container_add (GTK_CONTAINER (Login), eventbox35);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (eventbox35), fixed3);

  alignment15 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment15);
  gtk_fixed_put (GTK_FIXED (fixed3), alignment15, 29, 153);
  gtk_widget_set_size_request (alignment15, 134, 40);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_container_add (GTK_CONTAINER (alignment15), eventbox10);

  label_identifiant_admin = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label_identifiant_admin);
  gtk_container_add (GTK_CONTAINER (eventbox10), label_identifiant_admin);

  alignment16 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment16);
  gtk_fixed_put (GTK_FIXED (fixed3), alignment16, 29, 254);
  gtk_widget_set_size_request (alignment16, 134, 40);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_container_add (GTK_CONTAINER (alignment16), eventbox11);

  label_mdp_admin = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label_mdp_admin);
  gtk_container_add (GTK_CONTAINER (eventbox11), label_mdp_admin);

  alignment17 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment17);
  gtk_fixed_put (GTK_FIXED (fixed3), alignment17, 235, 164);
  gtk_widget_set_size_request (alignment17, 170, 26);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_container_add (GTK_CONTAINER (alignment17), eventbox12);

  identifiant_entry = gtk_entry_new ();
  gtk_widget_show (identifiant_entry);
  gtk_container_add (GTK_CONTAINER (eventbox12), identifiant_entry);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiant_entry), 8226);

  alignment18 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment18);
  gtk_fixed_put (GTK_FIXED (fixed3), alignment18, 235, 261);
  gtk_widget_set_size_request (alignment18, 170, 26);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_container_add (GTK_CONTAINER (alignment18), eventbox13);

  password_entry = gtk_entry_new ();
  gtk_widget_show (password_entry);
  gtk_container_add (GTK_CONTAINER (eventbox13), password_entry);
  gtk_entry_set_invisible_char (GTK_ENTRY (password_entry), 8226);

  alignment19 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment19);
  gtk_fixed_put (GTK_FIXED (fixed3), alignment19, 195, 320);
  gtk_widget_set_size_request (alignment19, 134, 35);

  eventbox14 = gtk_event_box_new ();
  gtk_widget_show (eventbox14);
  gtk_container_add (GTK_CONTAINER (alignment19), eventbox14);

  button_identifier_admin = gtk_button_new ();
  gtk_widget_show (button_identifier_admin);
  gtk_container_add (GTK_CONTAINER (eventbox14), button_identifier_admin);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button_identifier_admin), alignment20);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox7);

  image9 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox7), image9, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("S'identifier"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox7), label10, FALSE, FALSE, 0);

  alignment21 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment21);
  gtk_fixed_put (GTK_FIXED (fixed3), alignment21, 175, 376);
  gtk_widget_set_size_request (alignment21, 170, 35);

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_container_add (GTK_CONTAINER (alignment21), eventbox15);

  output_login = gtk_label_new ("");
  gtk_widget_show (output_login);
  gtk_container_add (GTK_CONTAINER (eventbox15), output_login);

  alignment43 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment43);
  gtk_fixed_put (GTK_FIXED (fixed3), alignment43, 195, 40);
  gtk_widget_set_size_request (alignment43, 134, 40);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_container_add (GTK_CONTAINER (alignment43), eventbox34);

  label13 = gtk_label_new (_("Sky Travel"));
  gtk_widget_show (label13);
  gtk_container_add (GTK_CONTAINER (eventbox34), label13);

  image26 = create_pixmap (Login, "avion.jpg");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed3), image26, 0, 0);
  gtk_widget_set_size_request (image26, 528, 416);

  g_signal_connect ((gpointer) button_identifier_admin, "clicked",
                    G_CALLBACK (on_button_identifier_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Login, Login, "Login");
  GLADE_HOOKUP_OBJECT (Login, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (Login, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Login, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Login, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (Login, label_identifiant_admin, "label_identifiant_admin");
  GLADE_HOOKUP_OBJECT (Login, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Login, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (Login, label_mdp_admin, "label_mdp_admin");
  GLADE_HOOKUP_OBJECT (Login, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Login, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (Login, identifiant_entry, "identifiant_entry");
  GLADE_HOOKUP_OBJECT (Login, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Login, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (Login, password_entry, "password_entry");
  GLADE_HOOKUP_OBJECT (Login, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Login, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (Login, button_identifier_admin, "button_identifier_admin");
  GLADE_HOOKUP_OBJECT (Login, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Login, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Login, image9, "image9");
  GLADE_HOOKUP_OBJECT (Login, label10, "label10");
  GLADE_HOOKUP_OBJECT (Login, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (Login, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (Login, output_login, "output_login");
  GLADE_HOOKUP_OBJECT (Login, alignment43, "alignment43");
  GLADE_HOOKUP_OBJECT (Login, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (Login, label13, "label13");
  GLADE_HOOKUP_OBJECT (Login, image26, "image26");

  return Login;
}

GtkWidget*
create_Ajout_agent (void)
{
  GtkWidget *Ajout_agent;
  GtkWidget *fixed4;
  GtkWidget *alignment22;
  GtkWidget *eventbox16;
  GtkWidget *label25;
  GtkWidget *alignment23;
  GtkWidget *eventbox17;
  GtkWidget *label_nom_agent_par_admin;
  GtkWidget *alignment24;
  GtkWidget *eventbox18;
  GtkWidget *label_prenom_agent_par_admin;
  GtkWidget *alignment25;
  GtkWidget *eventbox19;
  GtkWidget *label_sexe_agent_par_admin;
  GtkWidget *alignment26;
  GtkWidget *eventbox20;
  GtkWidget *label_numcin_agent_par_admin;
  GtkWidget *alignment27;
  GtkWidget *eventbox21;
  GtkWidget *label_numtel_agent_par_admin;
  GtkWidget *alignment28;
  GtkWidget *eventbox22;
  GtkWidget *label_datedenai_agent_par_admin;
  GtkWidget *alignment29;
  GtkWidget *eventbox23;
  GtkWidget *entry_ajout_nom_agent;
  GtkWidget *alignment30;
  GtkWidget *eventbox24;
  GtkWidget *entry_ajout_prenom_agent;
  GtkWidget *alignment33;
  GtkWidget *eventbox27;
  GtkWidget *entry_ajout_cin_agent;
  GtkWidget *alignment34;
  GtkWidget *eventbox28;
  GtkWidget *entry_ajout_tel_agent;
  GtkWidget *alignment38;
  GtkWidget *eventbox32;
  GtkWidget *button_ajouuut_agent;
  GtkWidget *alignment39;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label11;
  GtkWidget *alignment40;
  GtkWidget *eventbox33;
  GtkWidget *button_retour_ajout_vers_admin;
  GtkWidget *alignment41;
  GtkWidget *hbox9;
  GtkWidget *image13;
  GtkWidget *label12;
  GtkWidget *alignment44;
  GtkWidget *eventbox36;
  GtkWidget *entry_ajout_sexe_agent;
  GtkWidget *alignment45;
  GtkWidget *eventbox37;
  GtkWidget *entry_ajout_date_agent;
  GtkWidget *image19;

  Ajout_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajout_agent), _("Ajout_agent"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Ajout_agent), fixed4);

  alignment22 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment22);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment22, 153, 32);
  gtk_widget_set_size_request (alignment22, 134, 40);

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_container_add (GTK_CONTAINER (alignment22), eventbox16);

  label25 = gtk_label_new (_("<span foreground=\"darkcyan\"size=\"xx-large\"><i><b>Sky Travel</b></i></span>"));
  gtk_widget_show (label25);
  gtk_container_add (GTK_CONTAINER (eventbox16), label25);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  alignment23 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment23);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment23, 32, 152);
  gtk_widget_set_size_request (alignment23, 134, 45);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_container_add (GTK_CONTAINER (alignment23), eventbox17);

  label_nom_agent_par_admin = gtk_label_new (_("Nom"));
  gtk_widget_show (label_nom_agent_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox17), label_nom_agent_par_admin);

  alignment24 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment24);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment24, 32, 240);
  gtk_widget_set_size_request (alignment24, 134, 45);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_container_add (GTK_CONTAINER (alignment24), eventbox18);

  label_prenom_agent_par_admin = gtk_label_new (_("Prenom"));
  gtk_widget_show (label_prenom_agent_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox18), label_prenom_agent_par_admin);

  alignment25 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment25);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment25, 32, 336);
  gtk_widget_set_size_request (alignment25, 134, 45);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_container_add (GTK_CONTAINER (alignment25), eventbox19);

  label_sexe_agent_par_admin = gtk_label_new (_("Sexe"));
  gtk_widget_show (label_sexe_agent_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox19), label_sexe_agent_par_admin);

  alignment26 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment26);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment26, 32, 432);
  gtk_widget_set_size_request (alignment26, 134, 45);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_show (eventbox20);
  gtk_container_add (GTK_CONTAINER (alignment26), eventbox20);

  label_numcin_agent_par_admin = gtk_label_new (_("Num CIN"));
  gtk_widget_show (label_numcin_agent_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox20), label_numcin_agent_par_admin);

  alignment27 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment27);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment27, 32, 504);
  gtk_widget_set_size_request (alignment27, 134, 45);

  eventbox21 = gtk_event_box_new ();
  gtk_widget_show (eventbox21);
  gtk_container_add (GTK_CONTAINER (alignment27), eventbox21);

  label_numtel_agent_par_admin = gtk_label_new (_("Num tel"));
  gtk_widget_show (label_numtel_agent_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox21), label_numtel_agent_par_admin);

  alignment28 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment28);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment28, 32, 600);
  gtk_widget_set_size_request (alignment28, 134, 45);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_show (eventbox22);
  gtk_container_add (GTK_CONTAINER (alignment28), eventbox22);

  label_datedenai_agent_par_admin = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label_datedenai_agent_par_admin);
  gtk_container_add (GTK_CONTAINER (eventbox22), label_datedenai_agent_par_admin);

  alignment29 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment29);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment29, 200, 163);
  gtk_widget_set_size_request (alignment29, 200, 27);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_container_add (GTK_CONTAINER (alignment29), eventbox23);

  entry_ajout_nom_agent = gtk_entry_new ();
  gtk_widget_show (entry_ajout_nom_agent);
  gtk_container_add (GTK_CONTAINER (eventbox23), entry_ajout_nom_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ajout_nom_agent), 8226);

  alignment30 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment30);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment30, 200, 254);
  gtk_widget_set_size_request (alignment30, 200, 27);

  eventbox24 = gtk_event_box_new ();
  gtk_widget_show (eventbox24);
  gtk_container_add (GTK_CONTAINER (alignment30), eventbox24);

  entry_ajout_prenom_agent = gtk_entry_new ();
  gtk_widget_show (entry_ajout_prenom_agent);
  gtk_container_add (GTK_CONTAINER (eventbox24), entry_ajout_prenom_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ajout_prenom_agent), 8226);

  alignment33 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment33);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment33, 200, 444);
  gtk_widget_set_size_request (alignment33, 200, 27);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_container_add (GTK_CONTAINER (alignment33), eventbox27);

  entry_ajout_cin_agent = gtk_entry_new ();
  gtk_widget_show (entry_ajout_cin_agent);
  gtk_container_add (GTK_CONTAINER (eventbox27), entry_ajout_cin_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ajout_cin_agent), 8226);

  alignment34 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment34);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment34, 200, 513);
  gtk_widget_set_size_request (alignment34, 200, 27);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_container_add (GTK_CONTAINER (alignment34), eventbox28);

  entry_ajout_tel_agent = gtk_entry_new ();
  gtk_widget_show (entry_ajout_tel_agent);
  gtk_container_add (GTK_CONTAINER (eventbox28), entry_ajout_tel_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ajout_tel_agent), 8226);

  alignment38 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment38);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment38, 157, 680);
  gtk_widget_set_size_request (alignment38, 125, 35);

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_container_add (GTK_CONTAINER (alignment38), eventbox32);

  button_ajouuut_agent = gtk_button_new ();
  gtk_widget_show (button_ajouuut_agent);
  gtk_container_add (GTK_CONTAINER (eventbox32), button_ajouuut_agent);

  alignment39 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment39);
  gtk_container_add (GTK_CONTAINER (button_ajouuut_agent), alignment39);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment39), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox8), label11, FALSE, FALSE, 0);

  alignment40 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment40);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment40, 16, 712);
  gtk_widget_set_size_request (alignment40, 90, 30);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_container_add (GTK_CONTAINER (alignment40), eventbox33);

  button_retour_ajout_vers_admin = gtk_button_new ();
  gtk_widget_show (button_retour_ajout_vers_admin);
  gtk_container_add (GTK_CONTAINER (eventbox33), button_retour_ajout_vers_admin);

  alignment41 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment41);
  gtk_container_add (GTK_CONTAINER (button_retour_ajout_vers_admin), alignment41);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment41), hbox9);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox9), image13, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox9), label12, FALSE, FALSE, 0);

  alignment44 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment44);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment44, 200, 352);
  gtk_widget_set_size_request (alignment44, 200, 27);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_container_add (GTK_CONTAINER (alignment44), eventbox36);

  entry_ajout_sexe_agent = gtk_entry_new ();
  gtk_widget_show (entry_ajout_sexe_agent);
  gtk_container_add (GTK_CONTAINER (eventbox36), entry_ajout_sexe_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ajout_sexe_agent), 8226);

  alignment45 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment45);
  gtk_fixed_put (GTK_FIXED (fixed4), alignment45, 200, 608);
  gtk_widget_set_size_request (alignment45, 200, 27);

  eventbox37 = gtk_event_box_new ();
  gtk_widget_show (eventbox37);
  gtk_container_add (GTK_CONTAINER (alignment45), eventbox37);

  entry_ajout_date_agent = gtk_entry_new ();
  gtk_widget_show (entry_ajout_date_agent);
  gtk_container_add (GTK_CONTAINER (eventbox37), entry_ajout_date_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ajout_date_agent), 8226);

  image19 = create_pixmap (Ajout_agent, "1916561.jpg");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed4), image19, 0, 0);
  gtk_widget_set_size_request (image19, 424, 752);
  GTK_WIDGET_SET_FLAGS (image19, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (image19, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button_ajouuut_agent, "clicked",
                    G_CALLBACK (on_button_ajouuut_agent_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_ajout_vers_admin, "clicked",
                    G_CALLBACK (on_button_retour_ajout_vers_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_agent, Ajout_agent, "Ajout_agent");
  GLADE_HOOKUP_OBJECT (Ajout_agent, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (Ajout_agent, label25, "label25");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (Ajout_agent, label_nom_agent_par_admin, "label_nom_agent_par_admin");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (Ajout_agent, label_prenom_agent_par_admin, "label_prenom_agent_par_admin");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (Ajout_agent, label_sexe_agent_par_admin, "label_sexe_agent_par_admin");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (Ajout_agent, label_numcin_agent_par_admin, "label_numcin_agent_par_admin");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox21, "eventbox21");
  GLADE_HOOKUP_OBJECT (Ajout_agent, label_numtel_agent_par_admin, "label_numtel_agent_par_admin");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (Ajout_agent, label_datedenai_agent_par_admin, "label_datedenai_agent_par_admin");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (Ajout_agent, entry_ajout_nom_agent, "entry_ajout_nom_agent");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (Ajout_agent, entry_ajout_prenom_agent, "entry_ajout_prenom_agent");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (Ajout_agent, entry_ajout_cin_agent, "entry_ajout_cin_agent");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (Ajout_agent, entry_ajout_tel_agent, "entry_ajout_tel_agent");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (Ajout_agent, button_ajouuut_agent, "button_ajouuut_agent");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment39, "alignment39");
  GLADE_HOOKUP_OBJECT (Ajout_agent, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Ajout_agent, image12, "image12");
  GLADE_HOOKUP_OBJECT (Ajout_agent, label11, "label11");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (Ajout_agent, button_retour_ajout_vers_admin, "button_retour_ajout_vers_admin");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (Ajout_agent, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Ajout_agent, image13, "image13");
  GLADE_HOOKUP_OBJECT (Ajout_agent, label12, "label12");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment44, "alignment44");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (Ajout_agent, entry_ajout_sexe_agent, "entry_ajout_sexe_agent");
  GLADE_HOOKUP_OBJECT (Ajout_agent, alignment45, "alignment45");
  GLADE_HOOKUP_OBJECT (Ajout_agent, eventbox37, "eventbox37");
  GLADE_HOOKUP_OBJECT (Ajout_agent, entry_ajout_date_agent, "entry_ajout_date_agent");
  GLADE_HOOKUP_OBJECT (Ajout_agent, image19, "image19");

  gtk_widget_grab_focus (image19);
  gtk_widget_grab_default (image19);
  return Ajout_agent;
}

GtkWidget*
create_Modifier_agent (void)
{
  GtkWidget *Modifier_agent;
  GtkWidget *fixed5;
  GtkWidget *alignment46;
  GtkWidget *eventbox38;
  GtkWidget *label26;
  GtkWidget *alignment47;
  GtkWidget *eventbox39;
  GtkWidget *label15;
  GtkWidget *alignment48;
  GtkWidget *eventbox40;
  GtkWidget *label16;
  GtkWidget *alignment49;
  GtkWidget *eventbox41;
  GtkWidget *label17;
  GtkWidget *alignment50;
  GtkWidget *eventbox42;
  GtkWidget *label18;
  GtkWidget *alignment51;
  GtkWidget *eventbox43;
  GtkWidget *label19;
  GtkWidget *alignment52;
  GtkWidget *eventbox44;
  GtkWidget *label20;
  GtkWidget *alignment53;
  GtkWidget *eventbox45;
  GtkWidget *entry_modif_nom_agent;
  GtkWidget *alignment54;
  GtkWidget *eventbox46;
  GtkWidget *entry_modif_prenom_agent;
  GtkWidget *alignment55;
  GtkWidget *eventbox47;
  GtkWidget *entry_modif_numcin_agent;
  GtkWidget *alignment56;
  GtkWidget *eventbox48;
  GtkWidget *entry_modif_numtel_agent;
  GtkWidget *alignment57;
  GtkWidget *eventbox49;
  GtkWidget *button_modiffff_agent;
  GtkWidget *alignment63;
  GtkWidget *hbox12;
  GtkWidget *image18;
  GtkWidget *label23;
  GtkWidget *alignment59;
  GtkWidget *eventbox50;
  GtkWidget *button_retour_modif_vers_admin;
  GtkWidget *alignment60;
  GtkWidget *hbox11;
  GtkWidget *image17;
  GtkWidget *label22;
  GtkWidget *alignment61;
  GtkWidget *eventbox51;
  GtkWidget *entry_modif_sexe_agent;
  GtkWidget *alignment62;
  GtkWidget *eventbox52;
  GtkWidget *entry_modif_datenaiss_agent;
  GtkWidget *image25;

  Modifier_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifier_agent), _("Modifier_agent"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Modifier_agent), fixed5);

  alignment46 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment46);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment46, 153, 32);
  gtk_widget_set_size_request (alignment46, 134, 40);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_container_add (GTK_CONTAINER (alignment46), eventbox38);

  label26 = gtk_label_new (_("<span foreground=\"darkcyan\"size=\"xx-large\"><i><b>Sky Travel</b></i></span>"));
  gtk_widget_show (label26);
  gtk_container_add (GTK_CONTAINER (eventbox38), label26);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  alignment47 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment47);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment47, 32, 152);
  gtk_widget_set_size_request (alignment47, 134, 45);

  eventbox39 = gtk_event_box_new ();
  gtk_widget_show (eventbox39);
  gtk_container_add (GTK_CONTAINER (alignment47), eventbox39);

  label15 = gtk_label_new (_("Nom"));
  gtk_widget_show (label15);
  gtk_container_add (GTK_CONTAINER (eventbox39), label15);

  alignment48 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment48);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment48, 32, 240);
  gtk_widget_set_size_request (alignment48, 134, 45);

  eventbox40 = gtk_event_box_new ();
  gtk_widget_show (eventbox40);
  gtk_container_add (GTK_CONTAINER (alignment48), eventbox40);

  label16 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label16);
  gtk_container_add (GTK_CONTAINER (eventbox40), label16);

  alignment49 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment49);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment49, 32, 336);
  gtk_widget_set_size_request (alignment49, 134, 45);

  eventbox41 = gtk_event_box_new ();
  gtk_widget_show (eventbox41);
  gtk_container_add (GTK_CONTAINER (alignment49), eventbox41);

  label17 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label17);
  gtk_container_add (GTK_CONTAINER (eventbox41), label17);

  alignment50 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment50);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment50, 32, 432);
  gtk_widget_set_size_request (alignment50, 134, 45);

  eventbox42 = gtk_event_box_new ();
  gtk_widget_show (eventbox42);
  gtk_container_add (GTK_CONTAINER (alignment50), eventbox42);

  label18 = gtk_label_new (_("Num CIN"));
  gtk_widget_show (label18);
  gtk_container_add (GTK_CONTAINER (eventbox42), label18);

  alignment51 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment51);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment51, 32, 504);
  gtk_widget_set_size_request (alignment51, 134, 45);

  eventbox43 = gtk_event_box_new ();
  gtk_widget_show (eventbox43);
  gtk_container_add (GTK_CONTAINER (alignment51), eventbox43);

  label19 = gtk_label_new (_("Num tel"));
  gtk_widget_show (label19);
  gtk_container_add (GTK_CONTAINER (eventbox43), label19);

  alignment52 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment52);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment52, 32, 600);
  gtk_widget_set_size_request (alignment52, 134, 45);

  eventbox44 = gtk_event_box_new ();
  gtk_widget_show (eventbox44);
  gtk_container_add (GTK_CONTAINER (alignment52), eventbox44);

  label20 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label20);
  gtk_container_add (GTK_CONTAINER (eventbox44), label20);

  alignment53 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment53);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment53, 200, 163);
  gtk_widget_set_size_request (alignment53, 200, 27);

  eventbox45 = gtk_event_box_new ();
  gtk_widget_show (eventbox45);
  gtk_container_add (GTK_CONTAINER (alignment53), eventbox45);

  entry_modif_nom_agent = gtk_entry_new ();
  gtk_widget_show (entry_modif_nom_agent);
  gtk_container_add (GTK_CONTAINER (eventbox45), entry_modif_nom_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_nom_agent), 8226);

  alignment54 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment54);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment54, 200, 254);
  gtk_widget_set_size_request (alignment54, 200, 27);

  eventbox46 = gtk_event_box_new ();
  gtk_widget_show (eventbox46);
  gtk_container_add (GTK_CONTAINER (alignment54), eventbox46);

  entry_modif_prenom_agent = gtk_entry_new ();
  gtk_widget_show (entry_modif_prenom_agent);
  gtk_container_add (GTK_CONTAINER (eventbox46), entry_modif_prenom_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_prenom_agent), 8226);

  alignment55 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment55);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment55, 200, 444);
  gtk_widget_set_size_request (alignment55, 200, 27);

  eventbox47 = gtk_event_box_new ();
  gtk_widget_show (eventbox47);
  gtk_container_add (GTK_CONTAINER (alignment55), eventbox47);

  entry_modif_numcin_agent = gtk_entry_new ();
  gtk_widget_show (entry_modif_numcin_agent);
  gtk_container_add (GTK_CONTAINER (eventbox47), entry_modif_numcin_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_numcin_agent), 8226);

  alignment56 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment56);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment56, 200, 513);
  gtk_widget_set_size_request (alignment56, 200, 27);

  eventbox48 = gtk_event_box_new ();
  gtk_widget_show (eventbox48);
  gtk_container_add (GTK_CONTAINER (alignment56), eventbox48);

  entry_modif_numtel_agent = gtk_entry_new ();
  gtk_widget_show (entry_modif_numtel_agent);
  gtk_container_add (GTK_CONTAINER (eventbox48), entry_modif_numtel_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_numtel_agent), 8226);

  alignment57 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment57);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment57, 157, 680);
  gtk_widget_set_size_request (alignment57, 125, 35);

  eventbox49 = gtk_event_box_new ();
  gtk_widget_show (eventbox49);
  gtk_container_add (GTK_CONTAINER (alignment57), eventbox49);

  button_modiffff_agent = gtk_button_new ();
  gtk_widget_show (button_modiffff_agent);
  gtk_container_add (GTK_CONTAINER (eventbox49), button_modiffff_agent);

  alignment63 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment63);
  gtk_container_add (GTK_CONTAINER (button_modiffff_agent), alignment63);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment63), hbox12);

  image18 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox12), image18, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox12), label23, FALSE, FALSE, 0);

  alignment59 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment59);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment59, 16, 712);
  gtk_widget_set_size_request (alignment59, 90, 30);

  eventbox50 = gtk_event_box_new ();
  gtk_widget_show (eventbox50);
  gtk_container_add (GTK_CONTAINER (alignment59), eventbox50);

  button_retour_modif_vers_admin = gtk_button_new ();
  gtk_widget_show (button_retour_modif_vers_admin);
  gtk_container_add (GTK_CONTAINER (eventbox50), button_retour_modif_vers_admin);

  alignment60 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment60);
  gtk_container_add (GTK_CONTAINER (button_retour_modif_vers_admin), alignment60);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment60), hbox11);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox11), image17, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox11), label22, FALSE, FALSE, 0);

  alignment61 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment61);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment61, 200, 352);
  gtk_widget_set_size_request (alignment61, 200, 27);

  eventbox51 = gtk_event_box_new ();
  gtk_widget_show (eventbox51);
  gtk_container_add (GTK_CONTAINER (alignment61), eventbox51);

  entry_modif_sexe_agent = gtk_entry_new ();
  gtk_widget_show (entry_modif_sexe_agent);
  gtk_container_add (GTK_CONTAINER (eventbox51), entry_modif_sexe_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_sexe_agent), 8226);

  alignment62 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment62);
  gtk_fixed_put (GTK_FIXED (fixed5), alignment62, 200, 608);
  gtk_widget_set_size_request (alignment62, 200, 27);

  eventbox52 = gtk_event_box_new ();
  gtk_widget_show (eventbox52);
  gtk_container_add (GTK_CONTAINER (alignment62), eventbox52);

  entry_modif_datenaiss_agent = gtk_entry_new ();
  gtk_widget_show (entry_modif_datenaiss_agent);
  gtk_container_add (GTK_CONTAINER (eventbox52), entry_modif_datenaiss_agent);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_datenaiss_agent), 8226);

  image25 = create_pixmap (Modifier_agent, "1916561.jpg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed5), image25, 0, 0);
  gtk_widget_set_size_request (image25, 440, 744);

  g_signal_connect ((gpointer) button_modiffff_agent, "clicked",
                    G_CALLBACK (on_button_modiffff_agent_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_modif_vers_admin, "clicked",
                    G_CALLBACK (on_button_retour_modif_vers_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier_agent, Modifier_agent, "Modifier_agent");
  GLADE_HOOKUP_OBJECT (Modifier_agent, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment46, "alignment46");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (Modifier_agent, label26, "label26");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment47, "alignment47");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox39, "eventbox39");
  GLADE_HOOKUP_OBJECT (Modifier_agent, label15, "label15");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment48, "alignment48");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox40, "eventbox40");
  GLADE_HOOKUP_OBJECT (Modifier_agent, label16, "label16");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment49, "alignment49");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox41, "eventbox41");
  GLADE_HOOKUP_OBJECT (Modifier_agent, label17, "label17");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment50, "alignment50");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox42, "eventbox42");
  GLADE_HOOKUP_OBJECT (Modifier_agent, label18, "label18");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment51, "alignment51");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox43, "eventbox43");
  GLADE_HOOKUP_OBJECT (Modifier_agent, label19, "label19");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment52, "alignment52");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox44, "eventbox44");
  GLADE_HOOKUP_OBJECT (Modifier_agent, label20, "label20");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment53, "alignment53");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox45, "eventbox45");
  GLADE_HOOKUP_OBJECT (Modifier_agent, entry_modif_nom_agent, "entry_modif_nom_agent");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment54, "alignment54");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox46, "eventbox46");
  GLADE_HOOKUP_OBJECT (Modifier_agent, entry_modif_prenom_agent, "entry_modif_prenom_agent");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment55, "alignment55");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox47, "eventbox47");
  GLADE_HOOKUP_OBJECT (Modifier_agent, entry_modif_numcin_agent, "entry_modif_numcin_agent");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment56, "alignment56");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox48, "eventbox48");
  GLADE_HOOKUP_OBJECT (Modifier_agent, entry_modif_numtel_agent, "entry_modif_numtel_agent");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment57, "alignment57");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox49, "eventbox49");
  GLADE_HOOKUP_OBJECT (Modifier_agent, button_modiffff_agent, "button_modiffff_agent");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment63, "alignment63");
  GLADE_HOOKUP_OBJECT (Modifier_agent, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Modifier_agent, image18, "image18");
  GLADE_HOOKUP_OBJECT (Modifier_agent, label23, "label23");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment59, "alignment59");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox50, "eventbox50");
  GLADE_HOOKUP_OBJECT (Modifier_agent, button_retour_modif_vers_admin, "button_retour_modif_vers_admin");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment60, "alignment60");
  GLADE_HOOKUP_OBJECT (Modifier_agent, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Modifier_agent, image17, "image17");
  GLADE_HOOKUP_OBJECT (Modifier_agent, label22, "label22");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment61, "alignment61");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox51, "eventbox51");
  GLADE_HOOKUP_OBJECT (Modifier_agent, entry_modif_sexe_agent, "entry_modif_sexe_agent");
  GLADE_HOOKUP_OBJECT (Modifier_agent, alignment62, "alignment62");
  GLADE_HOOKUP_OBJECT (Modifier_agent, eventbox52, "eventbox52");
  GLADE_HOOKUP_OBJECT (Modifier_agent, entry_modif_datenaiss_agent, "entry_modif_datenaiss_agent");
  GLADE_HOOKUP_OBJECT (Modifier_agent, image25, "image25");

  return Modifier_agent;
}

GtkWidget*
create_profil_admin (void)
{
  GtkWidget *profil_admin;
  GtkWidget *fixed7;
  GtkWidget *alignment67;
  GtkWidget *eventbox56;
  GtkWidget *label31;
  GtkWidget *alignment68;
  GtkWidget *eventbox57;
  GtkWidget *label32;
  GtkWidget *alignment69;
  GtkWidget *eventbox58;
  GtkWidget *label33;
  GtkWidget *alignment70;
  GtkWidget *eventbox59;
  GtkWidget *label34;
  GtkWidget *alignment71;
  GtkWidget *eventbox60;
  GtkWidget *label35;
  GtkWidget *alignment72;
  GtkWidget *eventbox61;
  GtkWidget *label36;
  GtkWidget *alignment73;
  GtkWidget *eventbox62;
  GtkWidget *label37;
  GtkWidget *alignment74;
  GtkWidget *eventbox63;
  GtkWidget *label_nom_admin;
  GtkWidget *alignment75;
  GtkWidget *eventbox64;
  GtkWidget *label_prenom_admin;
  GtkWidget *alignment76;
  GtkWidget *eventbox65;
  GtkWidget *label_numcin_admin;
  GtkWidget *alignment77;
  GtkWidget *eventbox66;
  GtkWidget *label_numtel_admin;
  GtkWidget *alignment78;
  GtkWidget *eventbox67;
  GtkWidget *button_edit_profil_admin;
  GtkWidget *alignment84;
  GtkWidget *hbox15;
  GtkWidget *image24;
  GtkWidget *label40;
  GtkWidget *alignment80;
  GtkWidget *eventbox68;
  GtkWidget *button2;
  GtkWidget *alignment81;
  GtkWidget *hbox14;
  GtkWidget *image22;
  GtkWidget *label39;
  GtkWidget *alignment82;
  GtkWidget *eventbox69;
  GtkWidget *label_sexe_admin;
  GtkWidget *alignment83;
  GtkWidget *eventbox70;
  GtkWidget *label_datenaiss_admin;
  GtkWidget *image23;

  profil_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (profil_admin), _("profil_admin"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (profil_admin), fixed7);

  alignment67 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment67);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment67, 153, 32);
  gtk_widget_set_size_request (alignment67, 134, 40);

  eventbox56 = gtk_event_box_new ();
  gtk_widget_show (eventbox56);
  gtk_container_add (GTK_CONTAINER (alignment67), eventbox56);

  label31 = gtk_label_new (_("<span foreground=\"darkcyan\"size=\"xx-large\"><i><b>Sky Travel</b></i></span>"));
  gtk_widget_show (label31);
  gtk_container_add (GTK_CONTAINER (eventbox56), label31);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  alignment68 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment68);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment68, 32, 152);
  gtk_widget_set_size_request (alignment68, 134, 45);

  eventbox57 = gtk_event_box_new ();
  gtk_widget_show (eventbox57);
  gtk_container_add (GTK_CONTAINER (alignment68), eventbox57);

  label32 = gtk_label_new (_("Nom"));
  gtk_widget_show (label32);
  gtk_container_add (GTK_CONTAINER (eventbox57), label32);

  alignment69 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment69);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment69, 32, 240);
  gtk_widget_set_size_request (alignment69, 134, 45);

  eventbox58 = gtk_event_box_new ();
  gtk_widget_show (eventbox58);
  gtk_container_add (GTK_CONTAINER (alignment69), eventbox58);

  label33 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label33);
  gtk_container_add (GTK_CONTAINER (eventbox58), label33);

  alignment70 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment70);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment70, 32, 336);
  gtk_widget_set_size_request (alignment70, 134, 45);

  eventbox59 = gtk_event_box_new ();
  gtk_widget_show (eventbox59);
  gtk_container_add (GTK_CONTAINER (alignment70), eventbox59);

  label34 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label34);
  gtk_container_add (GTK_CONTAINER (eventbox59), label34);

  alignment71 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment71);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment71, 32, 432);
  gtk_widget_set_size_request (alignment71, 134, 45);

  eventbox60 = gtk_event_box_new ();
  gtk_widget_show (eventbox60);
  gtk_container_add (GTK_CONTAINER (alignment71), eventbox60);

  label35 = gtk_label_new (_("Num CIN"));
  gtk_widget_show (label35);
  gtk_container_add (GTK_CONTAINER (eventbox60), label35);

  alignment72 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment72);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment72, 32, 504);
  gtk_widget_set_size_request (alignment72, 134, 45);

  eventbox61 = gtk_event_box_new ();
  gtk_widget_show (eventbox61);
  gtk_container_add (GTK_CONTAINER (alignment72), eventbox61);

  label36 = gtk_label_new (_("Num tel"));
  gtk_widget_show (label36);
  gtk_container_add (GTK_CONTAINER (eventbox61), label36);

  alignment73 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment73);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment73, 32, 600);
  gtk_widget_set_size_request (alignment73, 134, 45);

  eventbox62 = gtk_event_box_new ();
  gtk_widget_show (eventbox62);
  gtk_container_add (GTK_CONTAINER (alignment73), eventbox62);

  label37 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label37);
  gtk_container_add (GTK_CONTAINER (eventbox62), label37);

  alignment74 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment74);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment74, 200, 163);
  gtk_widget_set_size_request (alignment74, 200, 27);

  eventbox63 = gtk_event_box_new ();
  gtk_widget_show (eventbox63);
  gtk_container_add (GTK_CONTAINER (alignment74), eventbox63);

  label_nom_admin = gtk_label_new ("");
  gtk_widget_show (label_nom_admin);
  gtk_container_add (GTK_CONTAINER (eventbox63), label_nom_admin);

  alignment75 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment75);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment75, 200, 254);
  gtk_widget_set_size_request (alignment75, 200, 27);

  eventbox64 = gtk_event_box_new ();
  gtk_widget_show (eventbox64);
  gtk_container_add (GTK_CONTAINER (alignment75), eventbox64);

  label_prenom_admin = gtk_label_new ("");
  gtk_widget_show (label_prenom_admin);
  gtk_container_add (GTK_CONTAINER (eventbox64), label_prenom_admin);

  alignment76 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment76);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment76, 200, 444);
  gtk_widget_set_size_request (alignment76, 200, 27);

  eventbox65 = gtk_event_box_new ();
  gtk_widget_show (eventbox65);
  gtk_container_add (GTK_CONTAINER (alignment76), eventbox65);

  label_numcin_admin = gtk_label_new ("");
  gtk_widget_show (label_numcin_admin);
  gtk_container_add (GTK_CONTAINER (eventbox65), label_numcin_admin);

  alignment77 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment77);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment77, 200, 513);
  gtk_widget_set_size_request (alignment77, 200, 27);

  eventbox66 = gtk_event_box_new ();
  gtk_widget_show (eventbox66);
  gtk_container_add (GTK_CONTAINER (alignment77), eventbox66);

  label_numtel_admin = gtk_label_new ("");
  gtk_widget_show (label_numtel_admin);
  gtk_container_add (GTK_CONTAINER (eventbox66), label_numtel_admin);

  alignment78 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment78);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment78, 157, 680);
  gtk_widget_set_size_request (alignment78, 125, 35);

  eventbox67 = gtk_event_box_new ();
  gtk_widget_show (eventbox67);
  gtk_container_add (GTK_CONTAINER (alignment78), eventbox67);

  button_edit_profil_admin = gtk_button_new ();
  gtk_widget_show (button_edit_profil_admin);
  gtk_container_add (GTK_CONTAINER (eventbox67), button_edit_profil_admin);

  alignment84 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment84);
  gtk_container_add (GTK_CONTAINER (button_edit_profil_admin), alignment84);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment84), hbox15);

  image24 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox15), image24, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox15), label40, FALSE, FALSE, 0);

  alignment80 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment80);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment80, 16, 712);
  gtk_widget_set_size_request (alignment80, 90, 30);

  eventbox68 = gtk_event_box_new ();
  gtk_widget_show (eventbox68);
  gtk_container_add (GTK_CONTAINER (alignment80), eventbox68);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (eventbox68), button2);

  alignment81 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment81);
  gtk_container_add (GTK_CONTAINER (button2), alignment81);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment81), hbox14);

  image22 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox14), image22, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox14), label39, FALSE, FALSE, 0);

  alignment82 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment82);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment82, 200, 352);
  gtk_widget_set_size_request (alignment82, 200, 27);

  eventbox69 = gtk_event_box_new ();
  gtk_widget_show (eventbox69);
  gtk_container_add (GTK_CONTAINER (alignment82), eventbox69);

  label_sexe_admin = gtk_label_new ("");
  gtk_widget_show (label_sexe_admin);
  gtk_container_add (GTK_CONTAINER (eventbox69), label_sexe_admin);

  alignment83 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment83);
  gtk_fixed_put (GTK_FIXED (fixed7), alignment83, 200, 608);
  gtk_widget_set_size_request (alignment83, 200, 27);

  eventbox70 = gtk_event_box_new ();
  gtk_widget_show (eventbox70);
  gtk_container_add (GTK_CONTAINER (alignment83), eventbox70);

  label_datenaiss_admin = gtk_label_new ("");
  gtk_widget_show (label_datenaiss_admin);
  gtk_container_add (GTK_CONTAINER (eventbox70), label_datenaiss_admin);

  image23 = create_pixmap (profil_admin, "1916561.jpg");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed7), image23, 0, 0);
  gtk_widget_set_size_request (image23, 424, 744);
  GTK_WIDGET_SET_FLAGS (image23, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (image23, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button_edit_profil_admin, "clicked",
                    G_CALLBACK (on_button_edit_profil_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button_retour_ajout_vers_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (profil_admin, profil_admin, "profil_admin");
  GLADE_HOOKUP_OBJECT (profil_admin, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment67, "alignment67");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox56, "eventbox56");
  GLADE_HOOKUP_OBJECT (profil_admin, label31, "label31");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment68, "alignment68");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox57, "eventbox57");
  GLADE_HOOKUP_OBJECT (profil_admin, label32, "label32");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment69, "alignment69");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox58, "eventbox58");
  GLADE_HOOKUP_OBJECT (profil_admin, label33, "label33");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment70, "alignment70");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox59, "eventbox59");
  GLADE_HOOKUP_OBJECT (profil_admin, label34, "label34");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment71, "alignment71");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox60, "eventbox60");
  GLADE_HOOKUP_OBJECT (profil_admin, label35, "label35");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment72, "alignment72");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox61, "eventbox61");
  GLADE_HOOKUP_OBJECT (profil_admin, label36, "label36");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment73, "alignment73");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox62, "eventbox62");
  GLADE_HOOKUP_OBJECT (profil_admin, label37, "label37");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment74, "alignment74");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox63, "eventbox63");
  GLADE_HOOKUP_OBJECT (profil_admin, label_nom_admin, "label_nom_admin");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment75, "alignment75");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox64, "eventbox64");
  GLADE_HOOKUP_OBJECT (profil_admin, label_prenom_admin, "label_prenom_admin");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment76, "alignment76");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox65, "eventbox65");
  GLADE_HOOKUP_OBJECT (profil_admin, label_numcin_admin, "label_numcin_admin");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment77, "alignment77");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox66, "eventbox66");
  GLADE_HOOKUP_OBJECT (profil_admin, label_numtel_admin, "label_numtel_admin");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment78, "alignment78");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox67, "eventbox67");
  GLADE_HOOKUP_OBJECT (profil_admin, button_edit_profil_admin, "button_edit_profil_admin");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment84, "alignment84");
  GLADE_HOOKUP_OBJECT (profil_admin, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (profil_admin, image24, "image24");
  GLADE_HOOKUP_OBJECT (profil_admin, label40, "label40");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment80, "alignment80");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox68, "eventbox68");
  GLADE_HOOKUP_OBJECT (profil_admin, button2, "button2");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment81, "alignment81");
  GLADE_HOOKUP_OBJECT (profil_admin, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (profil_admin, image22, "image22");
  GLADE_HOOKUP_OBJECT (profil_admin, label39, "label39");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment82, "alignment82");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox69, "eventbox69");
  GLADE_HOOKUP_OBJECT (profil_admin, label_sexe_admin, "label_sexe_admin");
  GLADE_HOOKUP_OBJECT (profil_admin, alignment83, "alignment83");
  GLADE_HOOKUP_OBJECT (profil_admin, eventbox70, "eventbox70");
  GLADE_HOOKUP_OBJECT (profil_admin, label_datenaiss_admin, "label_datenaiss_admin");
  GLADE_HOOKUP_OBJECT (profil_admin, image23, "image23");

  gtk_widget_grab_focus (image23);
  gtk_widget_grab_default (image23);
  return profil_admin;
}

GtkWidget*
create_Modifier_admin (void)
{
  GtkWidget *Modifier_admin;
  GtkWidget *fixed8;
  GtkWidget *alignment101;
  GtkWidget *eventbox85;
  GtkWidget *label55;
  GtkWidget *alignment102;
  GtkWidget *eventbox86;
  GtkWidget *label56;
  GtkWidget *alignment103;
  GtkWidget *eventbox87;
  GtkWidget *label57;
  GtkWidget *alignment104;
  GtkWidget *eventbox88;
  GtkWidget *label58;
  GtkWidget *alignment105;
  GtkWidget *eventbox89;
  GtkWidget *label59;
  GtkWidget *alignment106;
  GtkWidget *eventbox90;
  GtkWidget *label60;
  GtkWidget *alignment107;
  GtkWidget *eventbox91;
  GtkWidget *label61;
  GtkWidget *alignment108;
  GtkWidget *eventbox92;
  GtkWidget *entry_modif_nom_admin;
  GtkWidget *alignment109;
  GtkWidget *eventbox93;
  GtkWidget *entry_modif_prenom_admin;
  GtkWidget *alignment110;
  GtkWidget *eventbox94;
  GtkWidget *entry_modif_cin_admin;
  GtkWidget *alignment111;
  GtkWidget *eventbox95;
  GtkWidget *entry_modif_tel_admin;
  GtkWidget *alignment112;
  GtkWidget *eventbox96;
  GtkWidget *button_valider_modif_admin;
  GtkWidget *alignment118;
  GtkWidget *hbox19;
  GtkWidget *image32;
  GtkWidget *label64;
  GtkWidget *alignment114;
  GtkWidget *eventbox97;
  GtkWidget *button5;
  GtkWidget *alignment115;
  GtkWidget *hbox18;
  GtkWidget *image30;
  GtkWidget *label63;
  GtkWidget *alignment116;
  GtkWidget *eventbox98;
  GtkWidget *entry_modif_sexe_admin;
  GtkWidget *alignment117;
  GtkWidget *eventbox99;
  GtkWidget *entry_modif_date_admin;
  GtkWidget *image31;

  Modifier_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifier_admin), _("Modifier_admin"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (Modifier_admin), fixed8);

  alignment101 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment101);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment101, 153, 32);
  gtk_widget_set_size_request (alignment101, 134, 40);

  eventbox85 = gtk_event_box_new ();
  gtk_widget_show (eventbox85);
  gtk_container_add (GTK_CONTAINER (alignment101), eventbox85);

  label55 = gtk_label_new (_("<span foreground=\"darkcyan\"size=\"xx-large\"><i><b>Sky Travel</b></i></span>"));
  gtk_widget_show (label55);
  gtk_container_add (GTK_CONTAINER (eventbox85), label55);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  alignment102 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment102);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment102, 32, 152);
  gtk_widget_set_size_request (alignment102, 134, 45);

  eventbox86 = gtk_event_box_new ();
  gtk_widget_show (eventbox86);
  gtk_container_add (GTK_CONTAINER (alignment102), eventbox86);

  label56 = gtk_label_new (_("Nom"));
  gtk_widget_show (label56);
  gtk_container_add (GTK_CONTAINER (eventbox86), label56);

  alignment103 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment103);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment103, 32, 240);
  gtk_widget_set_size_request (alignment103, 134, 45);

  eventbox87 = gtk_event_box_new ();
  gtk_widget_show (eventbox87);
  gtk_container_add (GTK_CONTAINER (alignment103), eventbox87);

  label57 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label57);
  gtk_container_add (GTK_CONTAINER (eventbox87), label57);

  alignment104 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment104);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment104, 32, 336);
  gtk_widget_set_size_request (alignment104, 134, 45);

  eventbox88 = gtk_event_box_new ();
  gtk_widget_show (eventbox88);
  gtk_container_add (GTK_CONTAINER (alignment104), eventbox88);

  label58 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label58);
  gtk_container_add (GTK_CONTAINER (eventbox88), label58);

  alignment105 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment105);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment105, 32, 432);
  gtk_widget_set_size_request (alignment105, 134, 45);

  eventbox89 = gtk_event_box_new ();
  gtk_widget_show (eventbox89);
  gtk_container_add (GTK_CONTAINER (alignment105), eventbox89);

  label59 = gtk_label_new (_("Num CIN"));
  gtk_widget_show (label59);
  gtk_container_add (GTK_CONTAINER (eventbox89), label59);

  alignment106 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment106);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment106, 32, 504);
  gtk_widget_set_size_request (alignment106, 134, 45);

  eventbox90 = gtk_event_box_new ();
  gtk_widget_show (eventbox90);
  gtk_container_add (GTK_CONTAINER (alignment106), eventbox90);

  label60 = gtk_label_new (_("Num tel"));
  gtk_widget_show (label60);
  gtk_container_add (GTK_CONTAINER (eventbox90), label60);

  alignment107 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment107);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment107, 32, 600);
  gtk_widget_set_size_request (alignment107, 134, 45);

  eventbox91 = gtk_event_box_new ();
  gtk_widget_show (eventbox91);
  gtk_container_add (GTK_CONTAINER (alignment107), eventbox91);

  label61 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label61);
  gtk_container_add (GTK_CONTAINER (eventbox91), label61);

  alignment108 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment108);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment108, 200, 163);
  gtk_widget_set_size_request (alignment108, 200, 27);

  eventbox92 = gtk_event_box_new ();
  gtk_widget_show (eventbox92);
  gtk_container_add (GTK_CONTAINER (alignment108), eventbox92);

  entry_modif_nom_admin = gtk_entry_new ();
  gtk_widget_show (entry_modif_nom_admin);
  gtk_container_add (GTK_CONTAINER (eventbox92), entry_modif_nom_admin);
  gtk_entry_set_text (GTK_ENTRY (entry_modif_nom_admin), _("Zoghlami"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_nom_admin), 8226);

  alignment109 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment109);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment109, 200, 254);
  gtk_widget_set_size_request (alignment109, 200, 27);

  eventbox93 = gtk_event_box_new ();
  gtk_widget_show (eventbox93);
  gtk_container_add (GTK_CONTAINER (alignment109), eventbox93);

  entry_modif_prenom_admin = gtk_entry_new ();
  gtk_widget_show (entry_modif_prenom_admin);
  gtk_container_add (GTK_CONTAINER (eventbox93), entry_modif_prenom_admin);
  gtk_entry_set_text (GTK_ENTRY (entry_modif_prenom_admin), _("Amine"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_prenom_admin), 8226);

  alignment110 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment110);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment110, 200, 444);
  gtk_widget_set_size_request (alignment110, 200, 27);

  eventbox94 = gtk_event_box_new ();
  gtk_widget_show (eventbox94);
  gtk_container_add (GTK_CONTAINER (alignment110), eventbox94);

  entry_modif_cin_admin = gtk_entry_new ();
  gtk_widget_show (entry_modif_cin_admin);
  gtk_container_add (GTK_CONTAINER (eventbox94), entry_modif_cin_admin);
  gtk_entry_set_text (GTK_ENTRY (entry_modif_cin_admin), _("14765455"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_cin_admin), 8226);

  alignment111 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment111);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment111, 200, 513);
  gtk_widget_set_size_request (alignment111, 200, 27);

  eventbox95 = gtk_event_box_new ();
  gtk_widget_show (eventbox95);
  gtk_container_add (GTK_CONTAINER (alignment111), eventbox95);

  entry_modif_tel_admin = gtk_entry_new ();
  gtk_widget_show (entry_modif_tel_admin);
  gtk_container_add (GTK_CONTAINER (eventbox95), entry_modif_tel_admin);
  gtk_entry_set_text (GTK_ENTRY (entry_modif_tel_admin), _("99970207"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_tel_admin), 8226);

  alignment112 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment112);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment112, 157, 680);
  gtk_widget_set_size_request (alignment112, 125, 35);

  eventbox96 = gtk_event_box_new ();
  gtk_widget_show (eventbox96);
  gtk_container_add (GTK_CONTAINER (alignment112), eventbox96);

  button_valider_modif_admin = gtk_button_new ();
  gtk_widget_show (button_valider_modif_admin);
  gtk_container_add (GTK_CONTAINER (eventbox96), button_valider_modif_admin);

  alignment118 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment118);
  gtk_container_add (GTK_CONTAINER (button_valider_modif_admin), alignment118);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment118), hbox19);

  image32 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox19), image32, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox19), label64, FALSE, FALSE, 0);

  alignment114 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment114);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment114, 16, 712);
  gtk_widget_set_size_request (alignment114, 90, 30);

  eventbox97 = gtk_event_box_new ();
  gtk_widget_show (eventbox97);
  gtk_container_add (GTK_CONTAINER (alignment114), eventbox97);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (eventbox97), button5);

  alignment115 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment115);
  gtk_container_add (GTK_CONTAINER (button5), alignment115);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment115), hbox18);

  image30 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox18), image30, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox18), label63, FALSE, FALSE, 0);

  alignment116 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment116);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment116, 200, 352);
  gtk_widget_set_size_request (alignment116, 200, 27);

  eventbox98 = gtk_event_box_new ();
  gtk_widget_show (eventbox98);
  gtk_container_add (GTK_CONTAINER (alignment116), eventbox98);

  entry_modif_sexe_admin = gtk_entry_new ();
  gtk_widget_show (entry_modif_sexe_admin);
  gtk_container_add (GTK_CONTAINER (eventbox98), entry_modif_sexe_admin);
  gtk_entry_set_text (GTK_ENTRY (entry_modif_sexe_admin), _("Homme"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_sexe_admin), 8226);

  alignment117 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment117);
  gtk_fixed_put (GTK_FIXED (fixed8), alignment117, 200, 608);
  gtk_widget_set_size_request (alignment117, 200, 27);

  eventbox99 = gtk_event_box_new ();
  gtk_widget_show (eventbox99);
  gtk_container_add (GTK_CONTAINER (alignment117), eventbox99);

  entry_modif_date_admin = gtk_entry_new ();
  gtk_widget_show (entry_modif_date_admin);
  gtk_container_add (GTK_CONTAINER (eventbox99), entry_modif_date_admin);
  gtk_entry_set_text (GTK_ENTRY (entry_modif_date_admin), _("2-7-1997"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modif_date_admin), 8226);

  image31 = create_pixmap (Modifier_admin, "1916561.jpg");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed8), image31, 0, 0);
  gtk_widget_set_size_request (image31, 440, 744);

  g_signal_connect ((gpointer) button_valider_modif_admin, "clicked",
                    G_CALLBACK (on_button_valider_modif_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button_retour_modif_vers_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier_admin, Modifier_admin, "Modifier_admin");
  GLADE_HOOKUP_OBJECT (Modifier_admin, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment101, "alignment101");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox85, "eventbox85");
  GLADE_HOOKUP_OBJECT (Modifier_admin, label55, "label55");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment102, "alignment102");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox86, "eventbox86");
  GLADE_HOOKUP_OBJECT (Modifier_admin, label56, "label56");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment103, "alignment103");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox87, "eventbox87");
  GLADE_HOOKUP_OBJECT (Modifier_admin, label57, "label57");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment104, "alignment104");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox88, "eventbox88");
  GLADE_HOOKUP_OBJECT (Modifier_admin, label58, "label58");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment105, "alignment105");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox89, "eventbox89");
  GLADE_HOOKUP_OBJECT (Modifier_admin, label59, "label59");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment106, "alignment106");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox90, "eventbox90");
  GLADE_HOOKUP_OBJECT (Modifier_admin, label60, "label60");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment107, "alignment107");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox91, "eventbox91");
  GLADE_HOOKUP_OBJECT (Modifier_admin, label61, "label61");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment108, "alignment108");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox92, "eventbox92");
  GLADE_HOOKUP_OBJECT (Modifier_admin, entry_modif_nom_admin, "entry_modif_nom_admin");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment109, "alignment109");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox93, "eventbox93");
  GLADE_HOOKUP_OBJECT (Modifier_admin, entry_modif_prenom_admin, "entry_modif_prenom_admin");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment110, "alignment110");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox94, "eventbox94");
  GLADE_HOOKUP_OBJECT (Modifier_admin, entry_modif_cin_admin, "entry_modif_cin_admin");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment111, "alignment111");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox95, "eventbox95");
  GLADE_HOOKUP_OBJECT (Modifier_admin, entry_modif_tel_admin, "entry_modif_tel_admin");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment112, "alignment112");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox96, "eventbox96");
  GLADE_HOOKUP_OBJECT (Modifier_admin, button_valider_modif_admin, "button_valider_modif_admin");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment118, "alignment118");
  GLADE_HOOKUP_OBJECT (Modifier_admin, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Modifier_admin, image32, "image32");
  GLADE_HOOKUP_OBJECT (Modifier_admin, label64, "label64");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment114, "alignment114");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox97, "eventbox97");
  GLADE_HOOKUP_OBJECT (Modifier_admin, button5, "button5");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment115, "alignment115");
  GLADE_HOOKUP_OBJECT (Modifier_admin, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Modifier_admin, image30, "image30");
  GLADE_HOOKUP_OBJECT (Modifier_admin, label63, "label63");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment116, "alignment116");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox98, "eventbox98");
  GLADE_HOOKUP_OBJECT (Modifier_admin, entry_modif_sexe_admin, "entry_modif_sexe_admin");
  GLADE_HOOKUP_OBJECT (Modifier_admin, alignment117, "alignment117");
  GLADE_HOOKUP_OBJECT (Modifier_admin, eventbox99, "eventbox99");
  GLADE_HOOKUP_OBJECT (Modifier_admin, entry_modif_date_admin, "entry_modif_date_admin");
  GLADE_HOOKUP_OBJECT (Modifier_admin, image31, "image31");

  return Modifier_admin;
}

